export {
  type AppError,
  appError,
  badRequest,
  companyDomainTaken,
  companyNotFound,
  conflict,
  databaseError,
  forbidden,
  invalidCredentials,
  noteNotFound,
  notFound,
  opportunityNotFound,
  personNotFound,
  rateLimited,
  socialConnectionNotFound,
  socialNoPage,
  socialOauthFailed,
  socialProviderNotConfigured,
  socialScopeMissing,
  socialStateInvalid,
  socialTokenExpired,
  taskNotFound,
  unauthorized,
  userNotFound,
  validationError,
  workspaceForbidden,
  workspaceNotFound,
  workspaceSlugTaken,
} from "./app-error";
export { ERROR_CODES, type ErrorCode } from "./codes";
