export {
  type AppError,
  appError,
  badRequest,
  companyCnpjTaken,
  companyDomainTaken,
  companyNotFound,
  conflict,
  databaseError,
  forbidden,
  formFieldInvalid,
  formNotFound,
  formNotPublished,
  integrationKeyInvalid,
  integrationKeyNotFound,
  invalidCredentials,
  landingPageNotFound,
  landingPageNotPublished,
  landingPageSlugTaken,
  noteNotFound,
  notFound,
  opportunityNotFound,
  personNotFound,
  rateLimited,
  scheduledPostInvalid,
  scheduledPostNotFound,
  socialConnectionNotFound,
  socialNoPage,
  socialOauthFailed,
  socialProviderNotConfigured,
  socialScopeMissing,
  socialStateInvalid,
  socialTokenExpired,
  storageNotConfigured,
  taskNotFound,
  unauthorized,
  userNotFound,
  validationError,
  workspaceForbidden,
  workspaceNotFound,
  workspaceSlugTaken,
} from "./app-error";
export { ERROR_CODES, type ErrorCode } from "./codes";
